version: '3.9'
services:
  api-frontsale:
    build:
      context: ./
      target: current
      args:
        - UID=node
    image: api-frontsale
    container_name: api-frontsale
    ports:
      - "3000:3000"
    hostname: api-frontsale
    volumes:
      - ./:/usr/local/share/app/
    networks:
      - api-frontsale

networks:
  api-frontsale:
